# Generated by Django 2.1.7 on 2019-09-23 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citiesapp', '0002_auto_20190923_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='id',
        ),
        migrations.RemoveField(
            model_name='country',
            name='id',
        ),
        migrations.RemoveField(
            model_name='events',
            name='id',
        ),
        migrations.RemoveField(
            model_name='place',
            name='id',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='id',
        ),
        migrations.RemoveField(
            model_name='state',
            name='id',
        ),
        migrations.RemoveField(
            model_name='stories',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.RemoveField(
            model_name='visa',
            name='id',
        ),
        migrations.AlterField(
            model_name='city',
            name='City_ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='country',
            name='CountryName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citiesapp.Place'),
        ),
        migrations.AlterField(
            model_name='country',
            name='Country_ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='events',
            name='Fest_ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='place',
            name='Place_ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='Restaurant_ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='state',
            name='State_ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stories',
            name='Article_ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='visa',
            name='Visa_ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
