# Generated by Django 2.1.7 on 2019-09-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citiesapp', '0003_auto_20190923_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='City_ID',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
