# Generated by Django 2.1.7 on 2019-09-23 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citiesapp', '0004_auto_20190923_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='Places',
        ),
        migrations.RemoveField(
            model_name='place',
            name='Country',
        ),
    ]
