# Generated by Django 2.1.7 on 2019-09-23 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citiesapp', '0005_auto_20190923_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countrie',
            fields=[
                ('Country_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('CountryName', models.CharField(max_length=20)),
                ('URL', models.CharField(max_length=20)),
                ('About', models.CharField(max_length=20)),
                ('Continent', models.CharField(max_length=20)),
                ('States', models.CharField(max_length=20)),
                ('Visa', models.CharField(max_length=20)),
                ('City', models.CharField(max_length=20)),
                ('Events', models.CharField(max_length=20)),
                ('Foods', models.CharField(max_length=20)),
                ('Photos', models.CharField(max_length=20)),
                ('Map', models.CharField(max_length=20)),
                ('Packages', models.CharField(max_length=20)),
                ('Travels', models.CharField(max_length=20)),
                ('Hotels', models.CharField(max_length=20)),
                ('Activities', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Plac',
            fields=[
                ('Place_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Places', models.CharField(max_length=20)),
                ('URL', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=20)),
                ('Themes', models.CharField(max_length=20)),
                ('FAQs', models.CharField(max_length=20)),
                ('Weather', models.CharField(max_length=20)),
                ('TimeRequired', models.CharField(max_length=20)),
                ('Timings', models.CharField(max_length=20)),
                ('EntryFee', models.CharField(max_length=20)),
                ('Reviews', models.CharField(max_length=20)),
                ('TripuppOpininon', models.CharField(max_length=20)),
                ('Food', models.CharField(max_length=20)),
                ('Photos', models.ImageField(upload_to='')),
                ('Videos', models.FileField(null=True, upload_to='videos/', verbose_name='')),
                ('Map', models.CharField(max_length=20)),
                ('HowToReach', models.CharField(max_length=200)),
                ('Articles', models.CharField(max_length=300)),
            ],
        ),
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
        migrations.RenameModel(
            old_name='Restaurants',
            new_name='Restaurant',
        ),
        migrations.RenameModel(
            old_name='Stories',
            new_name='Storie',
        ),
        migrations.RemoveField(
            model_name='country',
            name='CountryName',
        ),
        migrations.RemoveField(
            model_name='state',
            name='City',
        ),
        migrations.RenameModel(
            old_name='City',
            new_name='Citie',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.AddField(
            model_name='plac',
            name='City',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citiesapp.Citie'),
        ),
        migrations.AddField(
            model_name='plac',
            name='Country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citiesapp.Countrie'),
        ),
        migrations.AddField(
            model_name='plac',
            name='State',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citiesapp.State'),
        ),
    ]
